### ISSUE TITLE
NoMethodError: undefined method `<=' for nil:NilClass when adding parent

### ISSUE THREAD

**Issue by SAGV** [collectiveidea/awesome_nested_set#179]
When I'm trying to set up parent for a category, rails gives me a error:

``` ruby
undefined method `<=' for nil:NilClass
```

I really can't figure out why that error happens.

Here is my Category model:

``` ruby
class Category < ActiveRecord::Base
    acts_as_nested_set
  attr_accessible :description, :image_url, :title, :parent_id
  has_many :tools, :dependent => :destroy

end
```

Migrate file

``` ruby
class CreateCategories < ActiveRecord::Migration
  def change
    create_table :categories do |t|
      t.string :title
      t.text :description
      t.string :image_url

      #These ones are for nested set
      t.integer :parent_id
      t.integer :lft
      t.integer :rgt

      t.timestamps
    end
  end
end
```

I was trying to add parent through activeadmin and rails console. Both fail with the same error.
For example:

``` ruby
Category.last.move_to_child_of(1)
```

What's my mistake?

**Comment by conroywhitney** [comment]
Many, many years later, I ran into this same issue while using [elight/acts_as_commentable_with_threading](https://github.com/elight/acts_as_commentable_with_threading) which uses this ANS gem.

It looks like the root cause is when ANS is trying to compare the `lft` and `rgt` columns when moving an item around within the tree, it blows up comparing `nil`.

In my case, I had incorrectly changed the `lft` and `rgt` column types to `uuid` thinking that they were references to other tree nodes. When ANS tried to set them as integers, the column just remained `nil`, hence this comparison error.

Hope that helps people in the future!
