### ISSUE TITLE
awesome_nested_set breaks ActiveModel::Dirty

### ISSUE THREAD

**Issue by knarewski** [collectiveidea/awesome_nested_set#276]
Hello!

I discovered, that `awesome_nested_set` does not cooperate with `ActiveModel::Dirty#previous_changes` method.

Use case with nested set:

``` ruby
2.1.1 :001 > p = Post.create
2.1.1 :002 > p.text = 'Text'
2.1.1 :003 > p.save
2.1.1 :004 > p.previous_changes # => {} 
```

Without nested set:

``` ruby
2.1.1 :001 > p = Post.create
2.1.1 :002 > p.text = 'Text' 
2.1.1 :003 > p.save
2.1.1 :004 > p.previous_changes # => {"text"=>[nil, "Text"], "updated_at"=>[Mon, 18 Aug 2014 10:39:56 UTC +00:00, Mon, 18 Aug 2014 10:40:20 UTC +00:00]} 
```

Reproduced using Ruby 2.1.1, Rails 4.1.4 and awesome_nested_set 3.0.0.

I believe it may have something to do with `reload` mentioned in #213 , just wanted to explicitly point out this specific problem.

Thank you for the great gem though!

**Comment by bacrossland** [comment]
+1 Just ran into this issue myself. Going to take a look more in depth now based on the notes in #213.

**Comment by jcavalieri** [comment]
+1

**Comment by jadrol** [comment]
+1

**Comment by francisli** [comment]
Yikes, just ran into this myself, and am surprised this is still open after so many years given that this is breaking expected Rails behavior... will see if I can poke into the library and see what's going on...?

**Comment by francisli** [comment]
Ok, per comments in the referenced issue this is not going to be something easy to fix- reload is used quite a bit throughout the implementation.

As a half-workaround, how about updating the documentation to state that the acts_as_nested_set mixin should be called in the model class AFTER any after_ callbacks so that they are executed last, so that they don't clear changes states before other callbacks are executed? This doesn't help anyone who is relying on the changes methods outside of callbacks (hence a half-workaround)...

**Comment by dani-sc** [comment]
I've just spent too much time researching why the dirty tracking didn't work as expected. Thank you @francisli for your comment, I was able to make some kind of workaround.

It still would deserve a mention in the readme though.
